language: java
jdk:
  - oraclejdk8

env:
  global:
    - secure: f6a3XG9YuKvXZS6ICK0HGai0XWBSuHe6/WUGpewugToFvFaLqJ2nAUyMfXTjF+AhW49QmocJ0/FH6CsEbvoj9Jr+niJroHs3W24/BjuPe26mNxQUI8NVhc5BM2H+Kgq4vv7eJfDnO72XG7q8/Cq61BTamAa4LVfGYMFDk/q6uDredb2qe41j+Q0MlacPsRSo+iXSSTOL3hySWLKRCPOlCWMOdcVilpvKMlWdSbfCzM28lL75+CaevnHz2uXjBeWzBIvDRm7Rudh6OFN+3aaBV3Y8HuBzO+YE5zerpRbamwqWnTdm5xSiwCLwtMoiWdQPuf2mpKFs/rrdc00kQoU6gsG6fg5l9AdxHW2SFyRryMXQ3YZvELZghLOdxf+/YojIOq2WfzYfzRpgsrTHgLxdEOFOK/Nu3qX2taJ4l6027c8YaENVi1dSuGTqew5FiZJ7e2aiMwEgF+M37hYuWlnBQaIWEytZ9bSQ8Zxodtji1/LwSk3ODFG/l0LIvTr/HY85y0HmxRYUEkWLHGCnIoPXvhY9DbqrFMIR2AQVq9ET1inV+JsYgYHznv+uMQ+0pI9w2Q+FLKNXGjzqHM/2itSLhL/t7/kT2e08l5gmMhC/k5DQC912HjGeXhWbsV/AcsBk0UJop/PHeiMW0JD+WTb6E40filUEoe9G80n7/rkGbi0=
    - secure: g2CiJcWnjRYfEeNQwk2flWC/nZgPipk6tMZ6kOYIXNyTDGB/CZpYIRklCC3ujlGnjd+LT2a0UMl5V7PREzH/fG8OG34U7QyBXW2JXNx1ZsmIqLk6DMYwe/rIYjMepELPah+0u0dIgtquYhbYv3YkQ5jaCK67pzuLJdsJUUOYOsVU7UyBHrcLE4UfqRJI4Dhh+MnaMxuXwvTny1MpChf/RO6JRLuenboa5OEpj9sYUZ7GR9a59vJp6sQBDZE+dJjA7T0lxonvy5KT8CBaY7Sf5rdwU7U532QkWkBRFErsP4lhzjuFon9xaQ/t+ujDADI08hC/PWqNCifye/5Rmd98CZjlYPD6ma/GpQ38/50cEA3l+bZFM/9YuT3GLLmwQhswb/NFptkPl2NVUmKrpFWg7sMcfbPBJHr2oPxOx1Iu5khgc9DOJDYdYYbVylpr4kTXuq1rqo1XkS5H8/C2cFBP+5948OOROB//CAF7onybPzEstRHpcAhVM6CRbbj/xe+zGqX6+LlJnMTQrPUQgnmsS7upYddUCHAngzdztr9qSIzE46vTt+6rcUm8RQdZMVMISM2RIwQC7z+gVI4y7E8fpyq3qu1WgedxvwdwUMEm1k5NB0BV75umu5xpnemeC8kZIM+jdTcGzPb8UHVjvMyqz5NVapTGsL9lRVsG0hr1rnY=

sudo: false

install: true

script:
  - cd cast-on-core && mvn clean package deploy --settings settings.xml
 # - cd ../android && gradle clean check jacocoTestReport build

after_success:
  - pwd
  - mvn clean test jacoco:report coveralls:report
#- cd cast-on-core/android && ./gradlew jacocoTestReport coveralls